plugin_blacklist:
# common
- 3dr_radio
- actuator_control
- adsb
- altitude
- cam_imu_sync
- camera
- cellular_status
- companion_process_status
- debug_value
- esc_status
- esc_telemetry
- fake_gps
- ftp
- geofence
- gps_input
- gps_rtk
- gimbal_control
- guided_target
- hil
- home_position
- landing_target
- log_transfer
- mag_calibration_status
- mocap_pose_estimate
- mount_control
- nav_controller_output
- obstacle_distance
- odom
- onboard_computer_status
- play_tune
- px4flow
- rallypoint
- rangefinder
- safety_area
- setpoint_accel
- setpoint_position
- setpoint_trajectory
- setpoint_velocity
- terrain
- trajectory
- tunnel
- vfr_hud
- vibration
- wind_estimation
- waypoint
- wheel_odometry

plugin_whitelist: # 如果模块即被同时声明在plugin_blacklist和plugin_whitelist中，也会启动
- command
- distance_sensor
- global_position
- gps_status
- imu
- local_position
- manual_control
- param
- rc_io
- setpoint_raw
- setpoint_attitude
- sys_status
- sys_time
- vision_pose_estimate
- vision_speed_estimate
