import os
import shlex
from datetime import datetime
from typing import Any, Dict, List

import yaml

from sunray_test.dashboard.model import DashboardModel
from sunray_test.dashboard.types import DASHBOARD_UAV_ID, PACKAGE_ROOT, DashboardPlan


def run_generated_suite(args) -> int:
    if not args.suite_file:
        raise SystemExit("--run-suite requires --suite-file generated by the dashboard")
    if not args.platform:
        raise SystemExit("--run-suite requires --platform")

    environment = args.environment or ("sim" if args.sim else "exp")
    suite_override = load_suite_override(args.suite_file)
    suite_name = args.suite.strip() or str(suite_override.get("name", "dashboard")).strip()
    suite_name = suite_name or "dashboard"

    from sunray_test.core.runner import RunnerArgs, TestRunner

    runner = TestRunner(
        RunnerArgs(
            platform=args.platform,
            environment=environment,
            suite=suite_name,
            uav_id=DASHBOARD_UAV_ID,
            external_source=args.external_source,
            output_dir=args.output_dir,
            sn=args.sn,
            tester=args.tester,
            prompt_metadata=not args.no_prompt,
            suite_override=suite_override,
            suite_source=os.path.abspath(args.suite_file),
        )
    )
    return runner.run()


def default_output_dir() -> str:
    workspace_root = os.path.abspath(os.path.join(PACKAGE_ROOT, "..", ".."))
    return os.path.join(workspace_root, "tests", "output")


def resolve_output_dir(args) -> str:
    return os.path.abspath(args.output_dir or default_output_dir())


def runtime_suite_path(suite: Dict[str, Any], output_dir: str) -> str:
    suite_dir = os.path.join(output_dir, "generated_suites")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    return os.path.join(suite_dir, f"{timestamp}_{suite['name']}.yaml")


def write_runtime_suite(suite: Dict[str, Any], suite_path: str) -> None:
    os.makedirs(os.path.dirname(suite_path), exist_ok=True)
    with open(suite_path, "w", encoding="utf-8") as handle:
        yaml.safe_dump(suite, handle, allow_unicode=True, sort_keys=False)


def load_suite_override(path: str) -> Dict[str, Any]:
    suite_path = os.path.abspath(path)
    if not os.path.isfile(suite_path):
        raise SystemExit(f"suite file not found: {suite_path}")
    with open(suite_path, "r", encoding="utf-8") as handle:
        suite = yaml.safe_load(handle) or {}
    if not isinstance(suite, dict):
        raise SystemExit(f"suite file must be a YAML mapping: {suite_path}")
    return suite


def build_bringup_tabs(model: DashboardModel, plan: DashboardPlan) -> List[Dict[str, Any]]:
    return model.build_tabs("bringup", plan.environment, plan.runtime_state)


def build_runner_cli(
    args,
    model: DashboardModel,
    plan: DashboardPlan,
    suite_path: str,
    output_dir: str,
) -> str:
    command = [
        "--run-suite",
        "--platform",
        plan.profile,
        "--environment",
        plan.environment,
        "--suite",
        str(model.config.get("name", "dashboard")),
        "--suite-file",
        suite_path,
        "--output-dir",
        output_dir,
    ]
    if plan.external_source is not None:
        command.extend(["--external-source", str(plan.external_source)])
    if args.sn:
        command.extend(["--sn", args.sn])
    if args.tester:
        command.extend(["--tester", args.tester])
    if args.no_prompt:
        command.append("--no-prompt")
    return shlex.join(command)


def build_runner_tabs(
    model: DashboardModel,
    args,
    plan: DashboardPlan,
    suite_path: str,
    output_dir: str,
) -> List[Dict[str, Any]]:
    runner_cli = build_runner_cli(args, model, plan, suite_path, output_dir)
    template_variables = {
        **plan.runtime_state["template_variables"],
        "runner_cli": runner_cli,
        "suite_file": suite_path,
        "output_dir": output_dir,
        "profile": plan.profile,
        "environment": plan.environment,
    }
    state = {**plan.runtime_state, "template_variables": template_variables}
    return model.build_tabs("runner", plan.environment, state)


def build_manual_runner_command(
    model: DashboardModel,
    args,
    plan: DashboardPlan,
    suite_path: str,
    output_dir: str,
) -> str:
    runner_cli = build_runner_cli(args, model, plan, suite_path, output_dir)
    return "rosrun sunray_test run_test_dashboard.py " + runner_cli


def validate_dashboard_resources(
    profile: str,
    environment: str,
    suite: Dict[str, Any],
    uav_id: int,
    external_source: int,
) -> None:
    from sunray_test.core.suite_loader import (
        deep_merge,
        load_platform_config,
        load_yaml,
        load_yaml_dir,
        render_template,
    )

    config_root = os.path.join(PACKAGE_ROOT, "config")
    platform_data, environment_data, mission_files = load_rendered_config_sources(
        config_root,
        profile,
        environment,
        uav_id,
        external_source,
    )
    topics = merge_runtime_topics(platform_data, environment_data)
    missions = merge_runtime_missions(mission_files, environment_data, deep_merge)
    errors = find_missing_step_resources(suite, topics, missions)

    for required_topic in ("uav_state", "uav_control_cmd", "uav_setup"):
        if not str(topics.get(required_topic, "")).strip():
            errors.append(f"runtime profile missing required topic: {required_topic}")
    if errors:
        raise SystemExit("Dashboard 生成的测试计划资源校验失败:\n  - " + "\n  - ".join(errors))


def load_rendered_config_sources(
    config_root: str,
    profile: str,
    environment: str,
    uav_id: int,
    external_source: int,
):
    from sunray_test.core.suite_loader import load_platform_config, load_yaml, load_yaml_dir
    from sunray_test.core.suite_loader import render_template

    environment_path = os.path.join(config_root, "environments", f"{environment}.yaml")
    if not os.path.isfile(environment_path):
        raise SystemExit(f"environment config not found: {environment_path}")

    variables = {
        "uav_id": uav_id,
        "uav_name": f"/uav{uav_id}",
        "external_source": external_source if external_source is not None else "",
        "workspace_root": os.path.abspath(os.path.join(PACKAGE_ROOT, "..", "..")),
        "package_root": PACKAGE_ROOT,
    }
    platform_data = render_template(load_platform_config(config_root, profile), variables)
    environment_data = render_template(load_yaml(environment_path), variables)
    missions_dir = os.path.join(config_root, "missions")
    mission_files = render_template(load_yaml_dir(missions_dir), variables)
    return platform_data, environment_data, mission_files


def merge_runtime_topics(
    platform_data: Dict[str, Any],
    environment_data: Dict[str, Any],
) -> Dict[str, Any]:
    topics: Dict[str, Any] = {}
    topics.update(platform_data.get("topics", {}))
    topics.update(environment_data.get("topic_overrides", {}))
    return topics


def merge_runtime_missions(
    mission_files: Dict[str, Any],
    environment_data: Dict[str, Any],
    deep_merge,
) -> Dict[str, Any]:
    missions: Dict[str, Any] = {}
    for filename, mission_data in mission_files.items():
        mission_name = filename
        if isinstance(mission_data, dict):
            mission_name = mission_data.get("name", filename)
        missions[mission_name] = mission_data
    return deep_merge(missions, environment_data.get("missions", {}))


def find_missing_step_resources(
    suite: Dict[str, Any],
    topics: Dict[str, Any],
    missions: Dict[str, Any],
) -> List[str]:
    errors: List[str] = []
    for step in suite.get("steps", []):
        params = step.get("params", {}) if isinstance(step, dict) else {}
        topic_key = params.get("topic_key")
        if topic_key and not str(topics.get(str(topic_key), "")).strip():
            errors.append(f"{step.get('case', step)} missing topic key: {topic_key}")
        mission_key = params.get("mission_key")
        if mission_key and str(mission_key) not in missions:
            errors.append(f"{step.get('case', step)} missing mission: {mission_key}")
    return errors


def validate_dashboard_suite_schema(
    profile: str,
    environment: str,
    suite: Dict[str, Any],
    uav_id: int,
    external_source: int,
) -> None:
    from sunray_test.core.suite_loader import ConfigValidationError, load_config_triplet

    try:
        load_config_triplet(
            package_root=PACKAGE_ROOT,
            platform_name=profile,
            environment_name=environment,
            suite_name=suite["name"],
            uav_id=uav_id,
            external_source=external_source,
            suite_override=suite,
        )
    except ConfigValidationError as exc:
        raise SystemExit(f"Dashboard 生成的测试计划校验失败: {exc}") from exc
    except ModuleNotFoundError as exc:
        print(
            f"[dashboard] 跳过完整 ROS case 校验: 当前 Python 环境缺少模块 {exc.name}",
            flush=True,
        )


def write_suite_only_and_print(
    model: DashboardModel,
    args,
    plan: DashboardPlan,
    suite_path: str,
    output_dir: str,
) -> None:
    write_runtime_suite(plan.suite, suite_path)
    print(f"\n[dashboard] suite written: {suite_path}", flush=True)
    print(
        "[dashboard] manual runner command:\n"
        + build_manual_runner_command(model, args, plan, suite_path, output_dir),
        flush=True,
    )
    print("[dashboard] write-suite-only, not launching bringup or runner", flush=True)
