static_fromation:
  file_path:
    [
      "/home/yundrone/Sunray/sunray_formation/uav_formation/config/static_formation.yaml",
    ]

dynamic_fromation:
  file_path:
    [
      "/home/yundrone/Sunray/sunray_formation/uav_formation/config/circle.yaml",
      "/home/yundrone/Sunray/sunray_formation/uav_formation/config/figure_eight.yaml",
    ]

waypoint:
  file_path:
    [
      "/home/yundrone/Sunray/sunray_formation/uav_formation/config/waypoint.yaml",
    ]