uav_num: 6

formations:
# 三角阵型
  - name: triangle
    uav_pos:
      uav_1_x: 1.0
      uav_1_y: 0.0
      uav_1_z: 1
      uav_2_x: -1.0
      uav_2_y: 0.0
      uav_2_z: 1
      uav_3_x: -1.0
      uav_3_y: 1.0
      uav_3_z: 1
      uav_4_x: -1.0
      uav_4_y: -1.0
      uav_4_z: 1

# 矩阵阵型
  - name: square
    uav_pos:
      uav_1_x: 1.0
      uav_1_y: 1.0
      uav_1_z: 1
      uav_2_x: 1.0
      uav_2_y: -1.0
      uav_2_z: 1
      uav_3_x: -1.0
      uav_3_y: 1.0
      uav_3_z: 1
      uav_4_x: -1.0
      uav_4_y: -1.0
      uav_4_z: 1

# 一字阵型 横向
  - name: line_horizontal
    uav_pos:
      uav_1_x: 0.0
      uav_1_y: -1.5
      uav_1_z: 1.0
      uav_2_x: 0.0
      uav_2_y: -0.5
      uav_2_z: 1.0
      uav_3_x: 0.0
      uav_3_y: 0.5
      uav_3_z: 1
      uav_4_x: 0.0
      uav_4_y: 1.5
      uav_4_z: 1


# 一字阵型 纵向
  - name: line_vertical
    uav_pos:
      uav_1_x: 1.5
      uav_1_y: 0.0
      uav_1_z: 1.0
      uav_2_x: 0.5
      uav_2_y: 0.0
      uav_2_z: 1
      uav_3_x: -0.5
      uav_3_y: 0.0
      uav_3_z: 1
      uav_4_x: -1.5
      uav_4_y: 0.0
      uav_4_z: 1