# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from sunray_msgs/UAVState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class UAVState(genpy.Message):
  _md5sum = "70840d4a4eeda5052054ef9b0dd9272c"
  _type = "sunray_msgs/UAVState"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Header header

## 基本状态
uint8 uav_id                ## 无人机编号
bool connected              ## 是否与飞控建立连接
bool armed                  ## 是否解锁，true为已解锁，false则不是
string mode                 ## 飞控当前飞行模式

## 里程计状态
uint8 location_source               ## 无人机定位来源
bool odom_valid                     ## 里程计是否有效
float32[3] position                 ## [m]
float32[3] velocity                 ## [m/s]
float32[3] attitude                 ## [rad]
geometry_msgs/Quaternion attitude_q ## 四元数
float32[3] attitude_rate            ## [rad/s]

float32[3] pos_setpoint             ## [m]  位置控制目标点
float32[3] vel_setpoint             ## [m/s]  速度控制目标
float32[3] att_setpoint             ## [rad]  姿态控制目标

## 无人机电池状态
float32 battery_state               ## [V]
float32 battery_percetage           ## [0-1]

uint8 control_mode


    

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['header','uav_id','connected','armed','mode','location_source','odom_valid','position','velocity','attitude','attitude_q','attitude_rate','pos_setpoint','vel_setpoint','att_setpoint','battery_state','battery_percetage','control_mode']
  _slot_types = ['std_msgs/Header','uint8','bool','bool','string','uint8','bool','float32[3]','float32[3]','float32[3]','geometry_msgs/Quaternion','float32[3]','float32[3]','float32[3]','float32[3]','float32','float32','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,uav_id,connected,armed,mode,location_source,odom_valid,position,velocity,attitude,attitude_q,attitude_rate,pos_setpoint,vel_setpoint,att_setpoint,battery_state,battery_percetage,control_mode

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(UAVState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.uav_id is None:
        self.uav_id = 0
      if self.connected is None:
        self.connected = False
      if self.armed is None:
        self.armed = False
      if self.mode is None:
        self.mode = ''
      if self.location_source is None:
        self.location_source = 0
      if self.odom_valid is None:
        self.odom_valid = False
      if self.position is None:
        self.position = [0.] * 3
      if self.velocity is None:
        self.velocity = [0.] * 3
      if self.attitude is None:
        self.attitude = [0.] * 3
      if self.attitude_q is None:
        self.attitude_q = geometry_msgs.msg.Quaternion()
      if self.attitude_rate is None:
        self.attitude_rate = [0.] * 3
      if self.pos_setpoint is None:
        self.pos_setpoint = [0.] * 3
      if self.vel_setpoint is None:
        self.vel_setpoint = [0.] * 3
      if self.att_setpoint is None:
        self.att_setpoint = [0.] * 3
      if self.battery_state is None:
        self.battery_state = 0.
      if self.battery_percetage is None:
        self.battery_percetage = 0.
      if self.control_mode is None:
        self.control_mode = 0
    else:
      self.header = std_msgs.msg.Header()
      self.uav_id = 0
      self.connected = False
      self.armed = False
      self.mode = ''
      self.location_source = 0
      self.odom_valid = False
      self.position = [0.] * 3
      self.velocity = [0.] * 3
      self.attitude = [0.] * 3
      self.attitude_q = geometry_msgs.msg.Quaternion()
      self.attitude_rate = [0.] * 3
      self.pos_setpoint = [0.] * 3
      self.vel_setpoint = [0.] * 3
      self.att_setpoint = [0.] * 3
      self.battery_state = 0.
      self.battery_percetage = 0.
      self.control_mode = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3B().pack(_x.uav_id, _x.connected, _x.armed))
      _x = self.mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2B().pack(_x.location_source, _x.odom_valid))
      buff.write(_get_struct_3f().pack(*self.position))
      buff.write(_get_struct_3f().pack(*self.velocity))
      buff.write(_get_struct_3f().pack(*self.attitude))
      _x = self
      buff.write(_get_struct_4d().pack(_x.attitude_q.x, _x.attitude_q.y, _x.attitude_q.z, _x.attitude_q.w))
      buff.write(_get_struct_3f().pack(*self.attitude_rate))
      buff.write(_get_struct_3f().pack(*self.pos_setpoint))
      buff.write(_get_struct_3f().pack(*self.vel_setpoint))
      buff.write(_get_struct_3f().pack(*self.att_setpoint))
      _x = self
      buff.write(_get_struct_2fB().pack(_x.battery_state, _x.battery_percetage, _x.control_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.attitude_q is None:
        self.attitude_q = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 3
      (_x.uav_id, _x.connected, _x.armed,) = _get_struct_3B().unpack(str[start:end])
      self.connected = bool(self.connected)
      self.armed = bool(self.armed)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.mode = str[start:end]
      _x = self
      start = end
      end += 2
      (_x.location_source, _x.odom_valid,) = _get_struct_2B().unpack(str[start:end])
      self.odom_valid = bool(self.odom_valid)
      start = end
      end += 12
      self.position = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.velocity = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.attitude = _get_struct_3f().unpack(str[start:end])
      _x = self
      start = end
      end += 32
      (_x.attitude_q.x, _x.attitude_q.y, _x.attitude_q.z, _x.attitude_q.w,) = _get_struct_4d().unpack(str[start:end])
      start = end
      end += 12
      self.attitude_rate = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.pos_setpoint = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.vel_setpoint = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 12
      self.att_setpoint = _get_struct_3f().unpack(str[start:end])
      _x = self
      start = end
      end += 9
      (_x.battery_state, _x.battery_percetage, _x.control_mode,) = _get_struct_2fB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3B().pack(_x.uav_id, _x.connected, _x.armed))
      _x = self.mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2B().pack(_x.location_source, _x.odom_valid))
      buff.write(self.position.tostring())
      buff.write(self.velocity.tostring())
      buff.write(self.attitude.tostring())
      _x = self
      buff.write(_get_struct_4d().pack(_x.attitude_q.x, _x.attitude_q.y, _x.attitude_q.z, _x.attitude_q.w))
      buff.write(self.attitude_rate.tostring())
      buff.write(self.pos_setpoint.tostring())
      buff.write(self.vel_setpoint.tostring())
      buff.write(self.att_setpoint.tostring())
      _x = self
      buff.write(_get_struct_2fB().pack(_x.battery_state, _x.battery_percetage, _x.control_mode))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.attitude_q is None:
        self.attitude_q = geometry_msgs.msg.Quaternion()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 3
      (_x.uav_id, _x.connected, _x.armed,) = _get_struct_3B().unpack(str[start:end])
      self.connected = bool(self.connected)
      self.armed = bool(self.armed)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.mode = str[start:end]
      _x = self
      start = end
      end += 2
      (_x.location_source, _x.odom_valid,) = _get_struct_2B().unpack(str[start:end])
      self.odom_valid = bool(self.odom_valid)
      start = end
      end += 12
      self.position = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.velocity = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.attitude = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      _x = self
      start = end
      end += 32
      (_x.attitude_q.x, _x.attitude_q.y, _x.attitude_q.z, _x.attitude_q.w,) = _get_struct_4d().unpack(str[start:end])
      start = end
      end += 12
      self.attitude_rate = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.pos_setpoint = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.vel_setpoint = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 12
      self.att_setpoint = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      _x = self
      start = end
      end += 9
      (_x.battery_state, _x.battery_percetage, _x.control_mode,) = _get_struct_2fB().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
_struct_2fB = None
def _get_struct_2fB():
    global _struct_2fB
    if _struct_2fB is None:
        _struct_2fB = struct.Struct("<2fB")
    return _struct_2fB
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
