## parameter

uav_name: "uav"
uav_id: 1

## 定位来源枚举
# uint8 MOCAP=0
# uint8 VIOBOT=1
# uint8 GAZEBO=2
# uint8 FAKE_ODOM=3
# uint8 GPS = 4
# uint8 RTK = 5
# uint8 UWB = 6
# uint8 VINS = 7
# uint8 OPTICAL_FLOW = 8
# uint8 T265 = 9

external_source: 2
use_udp: false
uart_name: "/dev/ttyUSB0"
baudrate: 115200
udp_ip: "127.0.0.1"
rx_port: 14540
tx_port: 14541


control:
  uav_name: "TEST"
