plugin_blacklist:
- actuator_control
- adsb
- safety_area
- 3dr_radio
- cam_imu_sync
- altitude
- fake_gps
- gps_rtk
- hil
- home_position
- landing_target
- mocap_pose_estimate
- mount_control
- obstacle_distance
- vfr_hud
- waypoint
- wind_estimation
- px4flow
- global_position
- companion_process_status
- debug_value
- wheel_odometry
- vibration
- setpoint_position
- setpoint_accel
- setpoint_velocity
plugin_whitelist: []
#- 'sys_*'
