## parameter for uav_control
uav_name: "uav"
sim_mode: true
flag_printf: true

uav_control:
  ## 起飞高度
  Takeoff_height : 0.6
  ## 降落速度
  Land_speed : 0.2
  ##　上锁高度
  Disarm_height : 0.2

##　地理围栏
geo_fence:
  x_min: -30.0
  x_max: 30.0
  y_min: -30.0
  y_max: 30.0
  z_min: -0.5
  z_max: 30
