# 航点数据 第一个为起点 最后一个为终点
# 点数： 10 （最高支持10个点）
num_points: 10
# 航点1 起点
# 航点坐标
waypoint1:
  x: 0.0
  y: 0.0
  z: 1.0
# 航点2
# 航点坐标
waypoint2:
  x: 1.49
  y: 0.12
  z: 1.0
# 航点3
# 航点坐标
waypoint3:
  x: 3.47
  y: 1.65
  z: 1.0
# 航点4
# 航点坐标
waypoint4:
  x: 3.68
  y: 4.97
  z: 1.0
# 航点5
# 航点坐标
waypoint5:
  x: 2.37
  y: 6.40
  z: 1.0
# 航点6
# 航点坐标
waypoint6:
  x: -12.79
  y: 5.81
  z: 1.0
# 航点7
# 航点坐标
waypoint7:
  x: -13.88
  y: 4.15
  z: 1.0
# 航点8
# 航点坐标
waypoint8:
  x: -13.9
  y: 1.74
  z: 1.0
# 航点9
# 航点坐标
waypoint9:
  x: -12.11
  y: -0.47
  z: 1.0
# 航点10
# 航点坐标
waypoint10:
  x: 0.0
  y: 0.0
  z: 1.0
